### ISSUE TITLE
TimeoutError on password selector

### ISSUE THREAD

**Issue by MrPotatoPotatoPotato** [fawazahmed0/youtube-uploader#48]
After not having used this package for a few weeks, I just tried to use it once again.
But unfortunately every request I do gets timed out while waiting for an input selector.

(I am running the 1.3.22 version)

Stack:
`(node:6664) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector input[type="password"]:not([aria-hidden="true"]) failed: timeout 60000ms exceeded
    at new WaitTask (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:313:29)
    at Frame.waitForSelector (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (C:\Users\jason\Desktop\youtube bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2252:33)
    at login (C:\Users\jason\Desktop\youtube bot\node_modules\youtube-videos-uploader\upload.js:257:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async upload (C:\Users\jason\Desktop\youtube bot\node_modules\youtube-videos-uploader\upload.js:101:7)`

**Comment by fawazahmed0** [comment]
This is fixed in v1.3.24

**Comment by MrPotatoPotatoPotato** [comment]
I'm still facing the exact problem, even though im using 1.3.24 and puppeteer-extra-plugin-stealth@2.9.0

**Comment by MrPotatoPotatoPotato** [comment]
Okay if you add "await page.setBypassCSP(true)" on line 242 in upload.js, you actually will get futher. But now I get another error:
` UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath `//*[normalize-space(text())='Next']/parent::*[not(@disabled)]`
